[package]
name = "skip"
version = "1.0.0"
authors = []

[addresses]
skip = "_"
initia_std = "0x1"
std = "0x1"

[dev-addresses]
skip = "0x101"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "crates/../precompile/modules/initia_stdlib", rev = "main" }
