[package]
name = "skip"
version = "1.0.0"
authors = []

[addresses]
skip = "_"
initia_std = "0x1"
std = "0x1"

[dev-addresses]
skip = "0x10"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives.git", subdir = "initia_stdlib", rev = "v1.0.0-rc.1" }
