[package]
name = "skip"
version = "1.0.0"
authors = []

[addresses]
skip = ""
initia_std = "0x1"
std = "0x1"


[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "crates/../precompile/modules/initia_stdlib", rev = "v0.6.1" }
