[package]
name = "skip"
version = "1.0.0"
authors = []

[addresses]
skip = "0x101"
initia_std = "0x1"
std = "0x1"


[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/movevm.git", subdir = "crates/../precompile/modules/initia_stdlib", rev = "57ca7d5f09b9312bc21d7396df11cd76782330d4" }
