[package]
name = "testmodule"
version = "0.0.0"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "precompile/modules/initia_stdlib", rev = "main" }

[addresses]
std =  "0x1"
test_skip = "_"
initia_std = "0x1"